### ISSUE TITLE
Looking for more features, such as home value estimate or history

### ISSUE THREAD

**Issue by pengoder** [Bunsly/HomeHarvest#52]
Hi this is really impressive! Thank you so much for sharing. I am looking for more property history that we can see from the Realtor.com website or the home value estimate. Do you think if it's something that is valuable to add to this project? If so, can you direct me to their API doc so that I can add it myself if you don't have time to do this? Really appreciate it!

**Comment by ZacharyHampton** [comment]
Hey!

Regarding property history, it is possible to get, but due to the time complexity of getting it, we haven't added it to the software. The issue is the same with home valuations.

If you want to see the API documentation, run an introspection query on the gql endpoint in our code, and you can play around with it like that.
